<?php

use Tonight\MVC\Config;

Config::setNotFoundRoute('ErrorController@notFound');

Config::addRoute(
	'',
	'HomeController@index'
);

Config::addRoute(
	'erros/{type}',
	'ErrorController@show'
);
Config::addRoute(
	'erros/{type}/{message}',
	'ErrorController@show'
);

Config::addRoute(
	'login',
	'LoginController@index'
);
Config::addRoute(
	'login/acao',
	'LoginController@action'
);
Config::addRoute(
	'logout/acao',
	'LoginController@logout'
);

Config::addRoute(
	'pontos',
	'PointController@index'
);
Config::addRoute(
	'pontos/cadastrar',
	'PointController@register'
);
Config::addRoute(
	'pontos/acao/cadastrar',
	'PointController@registerAction'
);
Config::addRoute(
	'pontos/{id}/visualizar',
	'PointController@view'
);
Config::addRoute(
	'pontos/{id}/editar',
	'PointController@edit'
);
Config::addRoute(
	'pontos/{id}/acao/editar',
	'PointController@editAction'
);
Config::addRoute(
	'pontos/{id}/excluir',
	'PointController@delete'
);
Config::addRoute(
	'membros/pontos/{id}/alocar',
	'PointController@addUser'
);

Config::addRoute(
	'membros',
	'UserController@index'
);
Config::addRoute(
	'membros/cadastrar',
	'UserController@register'
);
Config::addRoute(
	'membros/acao/cadastrar',
	'UserController@registerAction'
);
Config::addRoute(
	'membros/{id}/visualizar',
	'UserController@view'
);
Config::addRoute(
	'membros/{id}/editar',
	'UserController@edit'
);
Config::addRoute(
	'membros/{id}/acao/editar',
	'UserController@editAction'
);
Config::addRoute(
	'membros/{id}/excluir',
	'UserController@delete'
);
Config::addRoute(
	'lideres/{id}/adicionar',
	'UserController@addLeader'
);
Config::addRoute(
	'lideres/{id}/remover',
	'UserController@removeLeader'
);
Config::addRoute(
	'pontos/membros/{id}/alocar',
	'UserController@addPoint'
);
Config::addRoute(
	'pontos/membros/{id}/desalocar',
	'UserController@removePoint'
);

Config::addRoute(
	'pesquisas',
	'SearchController@index'
);
Config::addRoute(
	'pesquisas/cadastrar',
	'SearchController@register'
);
Config::addRoute(
	'pesquisas/acao/cadastrar',
	'SearchController@registerAction'
);
Config::addRoute(
	'pesquisas/{id}/editar',
	'SearchController@edit'
);
Config::addRoute(
	'pesquisas/{id}/abrir',
	'SearchController@open'
);
Config::addRoute(
	'pesquisas/{id}/acao/editar',
	'SearchController@editAction'
);
Config::addRoute(
	'pesquisas/{id}/excluir',
	'SearchController@delete'
);
Config::addRoute(
	'pesquisas/{id}/resultados',
	'AnswerController@results'
);
Config::addRoute(
	'pesquisas/{id}/acao/responder',
	'AnswerController@action'
);

Config::addRoute(
	'pesquisas/{search}/perguntas/adicionar',
	'QuestionController@create'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/acao/adicionar',
	'QuestionController@createAction'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/{question}/editar',
	'QuestionController@edit'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/{question}/acao/editar',
	'QuestionController@editAction'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/{question}/acao/subir',
	'QuestionController@moveUp'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/{question}/acao/descer',
	'QuestionController@moveDown'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/{question}/excluir',
	'QuestionController@delete'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/{question}/alternativas/acao/adicionar',
	'OptionController@add'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/{question}/alternativas/{option}/editar',
	'OptionController@edit'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/{question}/alternativas/{option}/acao/subir',
	'OptionController@moveUp'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/{question}/alternativas/{option}/acao/descer',
	'OptionController@moveDown'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/{question}/alternativas/{option}/acao/editar',
	'OptionController@editAction'
);
Config::addRoute(
	'pesquisas/{search}/perguntas/{question}/alternativas/{option}/acao/remover',
	'OptionController@remove'
);